spring.application.name=user-service
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/usuarios
spring.datasource.username=root
spring.datasource.password=joaquim2006
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=F7+tY9gKx5n8tVq/eWBJmB+P6b8G0i/tUa1rZc3xO2L/n2dD5e+rA8dG9jH4kL7fJ6gKq0mN4oP1qQ==
sendgrid.api.key=${SENDGRID_API_KEY}
sendgrid.from.email=${SENDGRID_FROM_EMAIL}
sendgrid.template.id=${SENDGRID_TEMPLATE_ID}
